### PR TITLE
System sass+compass

### PR DESCRIPTION
**Pull request by sir-gawain**
Please find in this branch some changes regarding the sass version used and the inclusion of compass.
The second commit introduces the possibility to use the sass installed in the system ruby installation. This is useful for people already working with sass and using the package manager of their OS. The first commit changes the embedded jruby to a newer version, because for my system the original one could no load the sass code. The third commit adds a checkbox to activate compass, if its installed in the system (or search path). The last two commits are some cleanup stuff.

### CODE REVIEW

**Comment by jmarsault** [comment]
Some suggestions : 
I have no ruby installation but when I choose  "system sass runtime", it is the bundle version that appears.
Could you add a warning message instead?
It could be also a good idea to reorder the runtime options and move the "system sass runtime" before "external sass runtime" and maybe rename it to precise that is the Ruby installation?

Thank you sir-gawain.

**Comment by sir-gawain** [comment]
That is strange, but perhaps somehow the path for the bundled version goes to the search path of jruby if no system path can be found? My solution tries to load sass from the system path.
The order of the options was intentionally, because i think the system sass installation is more advanced, and if someone is not familiar with his/her system, that the bundled version should be used instead.
Btw the changes can also go to 7.1.1 branch (or whatever your main branch is, is couldnt find out).

**Comment by leodouglas** [comment]
I Hi
I tried to compile the Branch 7.2 for use with the 'COMPASS', but did not work.
How do I create the nbm?

**Comment by sir-gawain** [comment]
You have to install the jar from here: https://github.com/jmarsault/scss-editor/issues/9#issuecomment-8022658
Then compile in netbeans and create the nbm (context menu in project explorer).
This should work.

**Comment by leodouglas** [comment]
Ok, now it compiles. Thanks.

But, show this error on save: 
     LoadError: no such file to load -- compass

**Comment by sir-gawain** [comment]
This is the case, if no compass is installed.
The download package of sass and the bundled version do not contain compass.
You have to use the "system sass" and install compass in your systems ruby installation (as package or gem).
I'm not sure, if you can copy the sources of compass into a local sass installation, and use this, but you can try :)

**Comment by Barfly** [comment]
Hello,
Is it possible to have the nbm file?
It doesn't compile on my netbeans.

ps: what i need to have in the folder scss.editor/release/?
      only  "jruby-complete-1.7.0.preview2.jar"  &  "org-netbeans-modules-scss.jar" ?

**Comment by sir-gawain** [comment]
They must be in release/modules/ext/
I uploaded my nbm to this site https://github.com/downloads/sir-gawain/scss-editor/org-netbeans-modules-languages-scss.nbm
Its not signed and does not contain the embeded sass, but i hope its working nevertheless.

**Comment by Barfly** [comment]
Thanks for the .nbm file.
Unfortunately it doesn't work for me.
I configure the external sass runtime path like that : "C:\Ruby\lib\ruby\gems\1.9.1\gems\sass-3.2.1"

but when i go to a scss file and save it , netbeans open the windows configuration of the plugin with the following things:
-Invalid SASS/HAML installation directory
-and the sass/haml home is automatically overrided by this weird path "C:/Ruby/lib/ruby/vendor_ruby/1.9.1:C:/Ruby/lib/ruby/vendor_ruby/1.9.1/i386-msvcrt:C:/Ruby/lib/ruby/vendor_ruby"

the ouput scss engine say "<html><font color=red>Invalid SASS/HAML installation directory.</font></html>"

**Comment by sir-gawain** [comment]
Strange. The value in the path is set to the autodetected path for the system ruby runtime.
I'm not sure, why that is set, if you did not enable this option.
I will be on vacation next week, hope to be able to look into this after that.

**Comment by sir-gawain** [comment]
I made  new nbm with a fix for the problem with the overwritten path on external sass.
You can find it here:
https://github.com/downloads/sir-gawain/scss-editor/org-netbeans-modules-languages-scss.nbm

This nbm also includes sass 3.2.2 as bundled version of sass.

**Comment by Korri** [comment]
Would be cool if the Bundled version supported Compass. Or at least the "Enable COMPASS" option should be disabled if the Bundled Sass runtime is used.

**Pull request merged**
